package de.dhbw.karlsruhe.models;

public class Probability {

    private float PROBABILITY_FOR_NEW_NON_TERMINAL;
    private float PROBABILITY_FOR_TERMINAL;
    private float PROBABILITY_FOR_MULTIPLE_RIGHT_SIDE;
    private float PROBABILITY_FAVOUR_NON_TERMINAL_FOR_TERMINAL_ON_RIGHT_SIDE;
    private float PROBABILITY_FAVOUR_NON_TERMINAL_FOR_TERMINAL_IN_START_PRODUCTION;
    private final float DECREASING_PROBABILITY_FACTOR;

    public Probability(float PROBABILITY_FOR_NEW_NON_TERMINAL,
                       float PROBABILITY_FOR_TERMINAL,
                       float PROBABILITY_FOR_MULTIPLE_RIGHT_SIDE,
                       float PROBABILITY_FAVOUR_NON_TERMINAL_FOR_TERMINAL_ON_RIGHT_SIDE,
                       float PROBABILITY_FAVOUR_NON_TERMINAL_FOR_TERMINAL_IN_START_PRODUCTION,
                       float DECREASING_PROBABILITY_FACTOR) {
        this.PROBABILITY_FOR_NEW_NON_TERMINAL = PROBABILITY_FOR_NEW_NON_TERMINAL;
        this.PROBABILITY_FOR_TERMINAL = PROBABILITY_FOR_TERMINAL;
        this.PROBABILITY_FOR_MULTIPLE_RIGHT_SIDE = PROBABILITY_FOR_MULTIPLE_RIGHT_SIDE;
        this.PROBABILITY_FAVOUR_NON_TERMINAL_FOR_TERMINAL_ON_RIGHT_SIDE = PROBABILITY_FAVOUR_NON_TERMINAL_FOR_TERMINAL_ON_RIGHT_SIDE;
        this.PROBABILITY_FAVOUR_NON_TERMINAL_FOR_TERMINAL_IN_START_PRODUCTION = PROBABILITY_FAVOUR_NON_TERMINAL_FOR_TERMINAL_IN_START_PRODUCTION;
        this.DECREASING_PROBABILITY_FACTOR = DECREASING_PROBABILITY_FACTOR;
    }

    public float getPROBABILITY_FOR_NEW_NON_TERMINAL() {
        return PROBABILITY_FOR_NEW_NON_TERMINAL;
    }

    public float getPROBABILITY_FOR_TERMINAL() {
        return PROBABILITY_FOR_TERMINAL;
    }

    public float getPROBABILITY_FOR_MULTIPLE_RIGHT_SIDE() {
        return PROBABILITY_FOR_MULTIPLE_RIGHT_SIDE;
    }

    public float getPROBABILITY_FAVOUR_NON_TERMINAL_FOR_TERMINAL_ON_RIGHT_SIDE() {
        return PROBABILITY_FAVOUR_NON_TERMINAL_FOR_TERMINAL_ON_RIGHT_SIDE;
    }

    public float getPROBABILITY_FAVOUR_NON_TERMINAL_FOR_TERMINAL_IN_START_PRODUCTION() {
        return PROBABILITY_FAVOUR_NON_TERMINAL_FOR_TERMINAL_IN_START_PRODUCTION;
    }


    public void decrease_PROBABILITY_FOR_NEW_NON_TERMINAL() {
        this.PROBABILITY_FOR_NEW_NON_TERMINAL -= DECREASING_PROBABILITY_FACTOR;
    }

    public void decrease_PPROBABILITY_FOR_TERMINAL() {
        this.PROBABILITY_FOR_TERMINAL -= DECREASING_PROBABILITY_FACTOR;
    }

    public void decrease_PROBABILITY_FOR_MULTIPLE_RIGHT_SIDE() {
        this.PROBABILITY_FOR_MULTIPLE_RIGHT_SIDE -= DECREASING_PROBABILITY_FACTOR;
    }

    public void decrease_PROBABILITY_FAVOUR_NON_TERMINAL_FOR_TERMINAL_ON_RIGHT_SIDE() {
        this.PROBABILITY_FAVOUR_NON_TERMINAL_FOR_TERMINAL_ON_RIGHT_SIDE -= DECREASING_PROBABILITY_FACTOR;
    }

    public void decrease_PROBABILITY_FAVOUR_NON_TERMINAL_FOR_TERMINAL_IN_START_PRODUCTION() {
        this.PROBABILITY_FAVOUR_NON_TERMINAL_FOR_TERMINAL_IN_START_PRODUCTION -= DECREASING_PROBABILITY_FACTOR;
    }

}
